pre_install:
  - rm_apk: ["com.google.android.gms", "com.android.vending"]
  - rm_data: 
    - "data/com.google.android.gms"
    - "data/com.android.vending"
post_remove:
  - rm_apk: ["com.google.android.gms", "com.android.vending"]
  - rm_data: 
    - "data/com.google.android.gms"
    - "data/com.android.vending"
    - "system/package_cache/11/Phonesky-16"
    - "system/package_cache/11/GmsCore-16"
    - "system/package_cache/11/GoogleCalendarSyncAdapter-16"
    - "system/package_cache/11/GoogleServicesFramework-16"
 